//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjHouseWebAp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 地點名稱
    {
        public int 地點編號 { get; set; }
        public string 類型 { get; set; }
        public string 帳號 { get; set; }
        public string 名稱 { get; set; }
        public string 照片 { get; set; }
        public string 說明 { get; set; }
        public string 地址 { get; set; }
    }
}
